service:
  mode: debug
  port: 9999
database:
  db-type: mysql
  db-name: project_manager
  host: 127.0.0.1
  port: 3306
  username: root
  password: root
  max-idle-conns: 10
  max-open-conns: 200
  string-size: 256
  log-level: info
minio:
  endpoint: 127.0.0.1:9001
  access-Key: VZxH6MUmKkg8uKiAVh48
  secret-key: PDXSIQNG2KQIGGY919nVWENmMS1wzPUlNFH52IAd
zap:
  level: info
  max-size: 100
  max-age: 30
  max-backups: 10
  compress: true